---

services:
  directus:
    image: directus/directus:11.2.0
    depends_on:
      - postgresql-directus
      - valkey-directus
    environment:
      - SECRET=${DIRECTUS_SECRET}
      - DB_USER=${DIRECTUS_DB_USER}
      - DB_DATABASE=${DIRECTUS_DB_NAME}
      - DB_PASSWORD=${DIRECTUS_DB_PASSWORD}
      - DB_CLIENT=pg
      - DB_HOST=postgresql-directus
      - DB_PORT=5432
      - CACHE_ENABLED=true
      - CACHE_AUTO_PURGE=true
      - CACHE_STORE=redis
      - REDIS=redis://valkey-directus:6379
      - ADMIN_EMAIL=${DIRECTUS_ADMIN_EMAIL}
      - ADMIN_PASSWORD=${DIRECTUS_ADMIN_PASSWORD}
      - ADMIN_TOKEN=${DIRECTUS_ADMIN_TOKEN}
    volumes:
      - directus-uploads:/directus/uploads
      - directus-extensions:/directus/extensions
    networks:
      directus:
    ports:
      - 3002:8055

  valkey-directus:
    image: valkey/valkey:8.0.1
    volumes:
      - valkey-directus:/data
    networks:
      directus:

  postgresql-directus:
    image: postgres:13.16
    environment:
      - POSTGRES_USER=${DIRECTUS_DB_USER}
      - POSTGRES_DB=${DIRECTUS_DB_NAME}
      - POSTGRES_PASSWORD=${DIRECTUS_DB_PASSWORD}
    volumes:
      - postgresql-directus:/var/lib/postgresql/data
    networks:
      directus:

  postgresql-backend:
    image: postgres:13.16
    environment:
      - POSTGRES_USER=${BACKEND_DB_USER}
      - POSTGRES_DB=${BACKEND_DB_NAME}
      - POSTGRES_PASSWORD=${BACKEND_DB_PASSWORD}
    volumes:
      - postgresql-backend:/var/lib/postgresql/data
    networks:
      backend:

volumes:
  directus-uploads:
  directus-extensions:
  valkey-directus:
  postgresql-directus:
  postgresql-backend:

networks:
  directus:
  backend: