---

services:
  tousinclus-frontend:
    image: ghcr.io/equanoria/tousinclus/tousinclus-frontend:staging
    networks:
      traefik_traefik:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.tousinclus-frontend_staging.entrypoints=websecure
        - traefik.http.routers.tousinclus-frontend_staging.rule=Host(`staging.tousinclus.org`)
        - traefik.http.services.tousinclus-frontend_staging.loadbalancer.server.port=3000
        - traefik.http.routers.tousinclus-frontend_staging.tls=true
        - traefik.http.routers.tousinclus-frontend_staging.tls.certresolver=letsencrypt
        - traefik.http.middlewares.tousinclus-frontend_staging-auth.basicauth.users=${STAGING_USERS}
        - traefik.http.routers.tousinclus-frontend_staging.middlewares=tousinclus-frontend_staging-auth
    environment:
      - SOCKET_IO_URL=https://staging.tousinclus.org/api
      - BACKEND_URL=https://staging.tousinclus.org/api
      - DIRECTUS_URL=https://staging.cms.tousinclus.org

  tousinclus-backend:
    image: ghcr.io/equanoria/tousinclus/tousinclus-backend:staging
    networks:
      tousinclus-backend:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.tousinclus-backend_staging.entrypoints=websecure
        - traefik.http.routers.tousinclus-backend_staging.rule=Host(`staging.tousinclus.org`) && PathPrefix(`/api`)
        - traefik.http.services.tousinclus-backend_staging.loadbalancer.server.port=3000
        - traefik.http.routers.tousinclus-backend_staging.tls=true
        - traefik.http.routers.tousinclus-backend_staging.tls.certresolver=letsencrypt
        - traefik.http.middlewares.tousinclus-backend_staging-auth.basicauth.users=${STAGING_USERS}
        - traefik.http.routers.tousinclus-backend_staging.middlewares=tousinclus-backend_staging-auth
    environment:
      - REDIS_HOSTNAME=valkey-backend
      - REDIS_PORT=6379
      - MONGO_HOSTNAME=mongo-backend
      - MONGO_PORT=27017
      - MONGO_DATABASE=${BACKEND_DB_NAME}
      - MONGO_USERNAME=${BACKEND_DB_USER}
      - MONGO_PASSWORD=${BACKEND_DB_PASSWORD}

  mongo-backend:
    image: mongo:8.0.4-noble
    networks:
      tousinclus-backend:
      replicas: 1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${BACKEND_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${BACKEND_DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${BACKEND_DB_NAME}
    volumes:
      - mongo-backend:/data/db

  valkey-backend:
    image: valkey/valkey:8.0.1
    networks:
      tousinclus-backend:
      replicas: 1
    volumes:
      - valkey-backend:/data

  directus:
    image: ghcr.io/equanoria/tousinclus/directus:staging
    networks:
      directus:
      traefik_traefik:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.tousinclus-directus_staging.entrypoints=websecure
        - traefik.http.routers.tousinclus-directus_staging.rule=Host(`staging.cms.tousinclus.org`)
        - traefik.http.services.tousinclus-directus_staging.loadbalancer.server.port=8055
        - traefik.http.routers.tousinclus-directus_staging.tls=true
        - traefik.http.routers.tousinclus-directus_staging.tls.certresolver=letsencrypt
        - traefik.http.middlewares.tousinclus-directus_staging-auth.basicauth.users=${STAGING_USERS}
        - traefik.http.routers.tousinclus-directus_staging.middlewares=tousinclus-directus_staging-auth
    depends_on:
      - postgresql-directus
      - valkey-directus
    environment:
      - SECRET=${DIRECTUS_SECRET}
      - DB_USER=${DIRECTUS_DB_USER}
      - DB_DATABASE=${DIRECTUS_DB_NAME}
      - DB_PASSWORD=${DIRECTUS_DB_PASSWORD}
      - DB_CLIENT=pg
      - DB_HOST=postgresql-directus
      - DB_PORT=5432
      - CACHE_ENABLED=true
      - CACHE_AUTO_PURGE=true
      - CACHE_STORE=redis
      - PUBLIC_URL=${DIRECTUS_PUBLIC_URL}
      - REDIS=redis://valkey-directus:6379
      - ADMIN_EMAIL=${DIRECTUS_ADMIN_EMAIL}
      - ADMIN_PASSWORD=${DIRECTUS_ADMIN_PASSWORD}
      - ADMIN_TOKEN=${DIRECTUS_ADMIN_TOKEN}
      - EMAIL_TRANSPORT=smtp
      - EMAIL_FROM=${DIRECTUS_EMAIL_FROM}
      - EMAIL_SMTP_HOST=${DIRECTUS_EMAIL_SMTP_HOST}
      - EMAIL_SMTP_PORT=${DIRECTUS_EMAIL_SMTP_PORT}
      - EMAIL_SMTP_USER=${DIRECTUS_EMAIL_SMTP_USER}
      - EMAIL_SMTP_PASSWORD=${DIRECTUS_EMAIL_SMTP_PASSWORD}
      - SCHEMA_SYNC=IMPORT
      - CORS_ENABLED=true
      - CORS_ORIGIN=*
    volumes:
      - directus-uploads:/directus/uploads

  valkey-directus:
    image: valkey/valkey:8.0.1
    networks:
      directus:
      replicas: 1
    volumes:
      - valkey-directus:/data

  postgresql-directus:
    image: postgres:13.16
    networks:
      directus:
      replicas: 1
    environment:
      - POSTGRES_USER=${DIRECTUS_DB_USER}
      - POSTGRES_DB=${DIRECTUS_DB_NAME}
      - POSTGRES_PASSWORD=${DIRECTUS_DB_PASSWORD}
    volumes:
      - postgresql-directus:/var/lib/postgresql/data

  authentik:
    image: ghcr.io/equanoria/tousinclus/authentik:staging
    networks:
      authentik:
      traefik_traefik:
    command: server
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.tousinclus-authentik_staging.entrypoints=websecure
        - traefik.http.routers.tousinclus-authentik_staging.rule=Host(`staging.connect.tousinclus.org`)
        - traefik.http.services.tousinclus-authentik_staging.loadbalancer.server.port=9000
        - traefik.http.routers.tousinclus-authentik_staging.tls=true
        - traefik.http.routers.tousinclus-authentik_staging.tls.certresolver=letsencrypt
    depends_on:
      - postgresql-authentik
      - valkey-authentik
    environment:
      - AUTHENTIK_REDIS__HOST=valkey-authentik
      - AUTHENTIK_POSTGRESQL__HOST=postgresql-authentik
      - AUTHENTIK_POSTGRESQL__USER=${AUTHENTIK_DB_USER}
      - AUTHENTIK_POSTGRESQL__NAME=${AUTHENTIK_DB_NAME}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_DB_PASSWORD}
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
      - AUTHENTIK_BOOTSTRAP_EMAIL=${AUTHENTIK_BOOTSTRAP_EMAIL}
      - AUTHENTIK_BOOTSTRAP_PASSWORD=${AUTHENTIK_BOOTSTRAP_PASSWORD}
    volumes:
      - authentik-blueprints:/blueprints
      - authentik-media:/media
      - authentik-templates:/templates
  
  authentik-worker:
    image: ghcr.io/goauthentik/server:2024.12.3
    networks:
      authentik:
      replicas: 1
    command: worker
    environment:
      - AUTHENTIK_REDIS__HOST=valkey-authentik
      - AUTHENTIK_POSTGRESQL__HOST=postgresql-authentik
      - AUTHENTIK_POSTGRESQL__USER=${AUTHENTIK_DB_USER}
      - AUTHENTIK_POSTGRESQL__NAME=${AUTHENTIK_DB_NAME}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_DB_PASSWORD}
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
      - AUTHENTIK_BOOTSTRAP_EMAIL=${AUTHENTIK_BOOTSTRAP_EMAIL}
      - AUTHENTIK_BOOTSTRAP_PASSWORD=${AUTHENTIK_BOOTSTRAP_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - authentik-certs:/certs
      - authentik-blueprints:/blueprints
      - authentik-media:/media
      - authentik-templates:/templates
    depends_on:
      - postgresql-authentik
      - valkey-authentik

  valkey-authentik:
    image: valkey/valkey:8.0.1
    networks:
      authentik:
      replicas: 1
    volumes:
      - valkey-authentik:/data

  postgresql-authentik:
    image: postgres:13.16
    networks:
      authentik:
      replicas: 1
    environment:
      - POSTGRES_USER=${AUTHENTIK_DB_USER}
      - POSTGRES_DB=${AUTHENTIK_DB_NAME}
      - POSTGRES_PASSWORD=${AUTHENTIK_DB_PASSWORD}
    volumes:
      - postgresql-authentik:/var/lib/postgresql/data

volumes:
  mongo-backend:
  valkey-backend:
  directus-uploads:
  postgresql-directus:
  valkey-directus:
  authentik-certs:
  authentik-blueprints:
  authentik-media:
  authentik-templates:
  postgresql-authentik:
  valkey-authentik:

networks:
  directus:
  authentik:
  tousinclus-backend:
  traefik_traefik:
    external: true
