---

services:
  tousinclus-frontend:
    image: ghcr.io/equanoria/tousinclus-frontend:staging
    environment:
      - BACKEND_HOST=https://staging.api.tousinclus.org
    deploy:
      placement:
        constraints:
          - node.hostname == vm01
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.equanoria-tousinclus-frontend_staging.entrypoints=websecure
        - traefik.http.routers.equanoria-tousinclus-frontend_staging.rule=Host(`staging.tousinclus.org`)
        - traefik.http.services.equanoria-tousinclus-frontend_staging.loadbalancer.server.port=3000
        - traefik.http.routers.equanoria-tousinclus-frontend_staging.tls=true
        - traefik.http.routers.equanoria-tousinclus-frontend_staging.tls.certresolver=letsencrypt

  tousinclus-backend:
    image: ghcr.io/equanoria/tousinclus-backend:staging
    networks:
      tousinclus-backend:
    deploy:
      placement:
        constraints:
          - node.hostname == vm01
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.equanoria-tousinclus-backend_staging.entrypoints=websecure
        - traefik.http.routers.equanoria-tousinclus-backend_staging.rule=Host(`staging.api.tousinclus.org`)
        - traefik.http.services.equanoria-tousinclus-backend_staging.loadbalancer.server.port=3001
        - traefik.http.routers.equanoria-tousinclus-backend_staging.tls=true
        - traefik.http.routers.equanoria-tousinclus-backend_staging.tls.certresolver=letsencrypt

  directus:
    image: directus/directus:11.2.0
    depends_on:
      - postgresql-directus
      - valkey-directus
    environment:
      - SECRET=${DIRECTUS_SECRET}
      - DB_USER=${DIRECTUS_DB_USER}
      - DB_DATABASE=${DIRECTUS_DB_NAME}
      - DB_PASSWORD=${DIRECTUS_DB_PASSWORD}
      - DB_CLIENT=pg
      - DB_HOST=postgresql-directus
      - DB_PORT=5432
      - CACHE_ENABLED=true
      - CACHE_AUTO_PURGE=true
      - CACHE_STORE=redis
      - REDIS=redis://valkey-directus:6379
      - ADMIN_EMAIL=${DIRECTUS_ADMIN_EMAIL}
      - ADMIN_PASSWORD=${DIRECTUS_ADMIN_PASSWORD}
      - ADMIN_TOKEN=${DIRECTUS_ADMIN_TOKEN}
    volumes:
      - directus-uploads:/directus/uploads
      - directus-extensions:/directus/extensions
    networks:
      directus:
    ports:
      - 3002:8055

  valkey-directus:
    image: valkey/valkey:8.0.1
    volumes:
      - valkey-directus:/data
    networks:
      directus:

  postgresql-directus:
    image: postgres:13.16
    environment:
      - POSTGRES_USER=${DIRECTUS_DB_USER}
      - POSTGRES_DB=${DIRECTUS_DB_NAME}
      - POSTGRES_PASSWORD=${DIRECTUS_DB_PASSWORD}
    volumes:
      - postgresql-directus:/var/lib/postgresql/data
    networks:
      directus:

  postgresql-backend:
    image: postgres:13.16
    environment:
      - POSTGRES_USER=${BACKEND_DB_USER}
      - POSTGRES_DB=${BACKEND_DB_NAME}
      - POSTGRES_PASSWORD=${BACKEND_DB_PASSWORD}
    volumes:
      - postgresql-backend:/var/lib/postgresql/data
    networks:
      tousinclus-backend:

volumes:
  directus-uploads:
  directus-extensions:
  valkey-directus:
  postgresql-directus:
  postgresql-backend:

networks:
  directus:
  tousinclus-backend:
