name: Build and Deploy Docker images from staging to ghcr.io

on:
  pull_request:
    branches:
      - staging
    types:
      - closed

permissions: write-all

jobs:
  build:
    strategy:
      matrix:
        include:
          - image: tousinclus-frontend
            dockerfile: apps/frontend/Dockerfile
          - image: tousinclus-backend
            dockerfile: apps/backend/Dockerfile
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push tousinclus-frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/${{ matrix.image }}:staging

  update-stack:
    runs-on: ubuntu-latest
    environment: develop
    needs: build
    steps:
      - name: Update stack via Portainer GitOps webhook
        run: curl -k -X POST "${{ secrets.PORTAINER_WEBHOOK }}"
